id: P008127
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159423
  title: འབྲུག་པ་བཀའ་བརྒྱུད་ཀྱི་ལོ་རྒྱུས།
  author: ''
  volumes:
    aa4ad9d680da44caa43aeb700d8b2084:
      image_group_id: I2PD19608
      title: ''
      volume_number: 1
      total_pages: 338
ebook_metadata:
  title: འབྲུག་པ་བཀའ་བརྒྱུད་ཀྱི་ལོ་རྒྱུས།
  author: ''
  sku: P008127
  cover: cover.jpg
  layers:
  - pagination
